### ISSUE TITLE
python required

### ISSUE THREAD

**Issue by mikefills** [gist-run/gist-run#21]
I get lots of errors when running `npm install`, it says python is required.
Maybe add that to the readme?

```
D:\Projects\gist-run\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\gist-run\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by jdanyow** [comment]
this is just a general issue with node/npm and windows.  Have you installed a new version of nodejs lately?  Should clear it up.

**Comment by mikefills** [comment]
OK, now I have latest stable npm v3.8.0
and I tried again in a new directory, still getting same error on these two modules:

- bufferutil
- utf-8-validate

any hints how to fix this would be great, thanks

```
D:\Projects\gistrun2\gist-run>npm install

> bufferutil@1.2.1 install D:\Projects\gistrun2\gist-run\node_modules\bufferutil
> node-gyp rebuild


D:\Projects\gistrun2\gist-run\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myUser\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\gistrun2\gist-run\node_modules\bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install D:\Projects\gistrun2\gist-run\node_modules\utf-8-validate
> node-gyp rebuild


D:\Projects\gistrun2\gist-run\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Users\myUser\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myUser\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Projects\gistrun2\gist-run\node_modules\utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN optional Skipping failed optional dependency /browser-sync/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8

D:\Projects\gistrun2\gist-run>npm version
{ 'aurelia-skeleton-navigation': '1.0.0-beta.1.0.4',
  npm: '3.8.0',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '46',
  node: '4.2.4',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

**Comment by mikefills** [comment]
btw, bufferutil seems unreliable and no longer maintained: https://github.com/websockets/bufferutil/issues/36

**Comment by mikefills** [comment]
I run `gulp watch` with no errors, but in web-browser Gulp splash screen appears then page is blank.
Looking to the console errors in Chrome and I see

`GET http://localhost:3000/ net::ERR_CONNECTION_REFUSED
execute @ worker-activator.js:6p 
@ system.src.js:4434p 
@ system.src.js:4434p 
@ system.src.js:4434p 
@ system.src.js:4434
execute @ system.src.js:4434b @ system.src.js:4434x @ system.src.js:4434p @ system.src.js:4434h @ system.src.js:4434(anonymous function) @ system.src.js:4434h @ shim.min.js:1773(anonymous function) @ shim.min.js:1778e @ shim.min.js:1958`

**Comment by mikefills** [comment]
I'd like to try contribute to gist run once I get this going...

**Comment by mikefills** [comment]
@jdanyow checking the code I just realized you're using an iframe:
```
const iframe = document.createElement('iframe');
iframe.setAttribute('src', workerPage);
iframe.setAttribute('style', 'display: none');
document.body.appendChild(iframe);
```
workerPage `is http://localhost:3000` . Do I need to start a new webserver for that? how?

**Comment by mikefills** [comment]
OH, there's also another project dedicated to the worker :dancer:
